# Sandwich Bot Configuration Example
# Copy this to config.toml and customize for your needs

[rpc]
# Use a premium RPC for best results (Helius, QuickNode, Triton)
http_url = "https://api.mainnet-beta.solana.com"
ws_url = "wss://api.mainnet-beta.solana.com"
commitment = "confirmed"
timeout_seconds = 30
max_retries = 3

[wallet]
# Path to your wallet keypair (or set WALLET_KEYPAIR_PATH env var)
keypair_path = "~/.config/solana/id.json"
# Maximum SOL to use per trade
max_position_size = 1.0

[strategy]
# Minimum target transaction volume in USD
min_target_volume = 10000.0
# Maximum target transaction volume in USD
max_target_volume = 1000000.0
# Minimum profit required (in SOL)
min_profit_sol = 0.01
# Minimum profit percentage
min_profit_percentage = 0.5
# Maximum slippage tolerance (percentage)
max_slippage = 1.0
# Priority fee in lamports
priority_fee = 10000
# Use Jito MEV for bundled transactions
use_jito = true

[dex.raydium]
enabled = true
program_id = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"
min_liquidity_usd = 50000.0

[dex.orca]
enabled = true
program_id = "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc"
min_liquidity_usd = 50000.0

[dex.jupiter]
enabled = true
program_id = "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"
min_liquidity_usd = 50000.0

[risk]
# Maximum concurrent trades
max_concurrent_trades = 3
# Stop-loss percentage
stop_loss_percentage = 5.0
# Maximum daily loss in SOL
max_daily_loss = 5.0
# Circuit breaker: pause after N consecutive losses
circuit_breaker_losses = 5

