# NFT Mint Bot Configuration Example
# Copy this to config.toml and customize

[rpc]
http_url = "https://api.mainnet-beta.solana.com"
ws_url = "wss://api.mainnet-beta.solana.com"
commitment = "confirmed"
timeout_seconds = 30

[wallets]
primary_keypair_path = "~/.config/solana/id.json"
# Add multiple wallets for higher success rate
additional_keypairs = [
    # "wallet2.json",
    # "wallet3.json",
]
max_sol_per_wallet = 5.0

# Configure projects to mint
[[projects]]
name = "Example NFT Project"
candy_machine_id = "CandyMachineAddress111111111111111111111111"
mint_start_time = 1699999999  # Unix timestamp (optional)
mint_price = 1.0  # SOL
max_mints_per_wallet = 3
enabled = true

# Add more projects as needed
# [[projects]]
# name = "Another Project"
# candy_machine_id = "..."
# enabled = false

[strategy]
priority_fee = 100000         # High priority for fast execution
mint_attempts = 3             # Retry up to 3 times
attempt_delay_ms = 100        # 100ms between attempts
prebuild_transactions = true  # Pre-build txs for speed
multi_wallet_enabled = false  # Use multiple wallets

[risk]
max_concurrent_mints = 5      # Max simultaneous mints
max_total_spend = 10.0        # Max SOL to spend total
circuit_breaker_failures = 10 # Stop after N failures

